import CategoryPage, { Project } from "./CategoryPage";

const Corporate = () => {
  const projects: Project[] = [
    {
      id: 1,
      title: "Concentrix Daksh Services India Pvt. Ltd.",
      images: [],
      description: "Large-scale BPO corporate office interiors.",
      client: "Concentrix Daksh Services India Pvt. Ltd.",
      location: "Gurgaon",
      architect: "Vijay Punjabi Consultants Pvt. Ltd., Mumbai",
      value: "₹14.89 Cr",
      duration: "6 Months",
      scope: "Interior Works",
      area: "2,98,000 sq.ft",
    },
    {
      id: 2,
      title: "S. P. Jain School of Global Management – Kurla",
      images: [],
      description: "Academic corporate facility with classrooms and admin spaces.",
      client: "S. P. Jain School of Global Management",
      location: "Mumbai",
      architect: "Rajesh Patel Consultants Pvt. Ltd., Mumbai",
      value: "₹6.25 Cr",
      duration: "3 Months",
      scope: "Interior & MEP Works",
      area: "33,000 sq.ft",
    },
    {
      id: 3,
      title: "S. P. Jain School of Global Management – Kamala Mills",
      images: [],
      description: "Executive education campus in a premium business district.",
      client: "S. P. Jain School of Global Management",
      location: "Mumbai",
      architect: "Rajesh Patel Consultants Pvt. Ltd., Mumbai",
      value: "₹5.32 Cr",
      duration: "4 Months",
      scope: "Interior & MEP Works",
      area: "19,500 sq.ft",
    },
    {
      id: 4,
      title: "AION India Investment Advisors Pvt. Ltd.",
      images: [],
      description: "Investment advisory corporate office.",
      client: "AION India Investment Advisors Pvt. Ltd.",
      location: "Mumbai",
      architect: "Imagineers, Mumbai",
      value: "₹4.10 Cr",
      duration: "3 Months",
      scope: "Interior & MEP Works",
      area: "8,775 sq.ft",
    },
    {
      id: 5,
      title: "Panasonic India Ltd. – Mumbai",
      images: [],
      description: "Corporate headquarters interiors.",
      client: "Panasonic India Ltd.",
      location: "Mumbai",
      architect: "DAIKO, Japan",
      value: "₹9.19 Cr",
      duration: "6 Months",
      scope: "Interior Works",
      area: "38,500 sq.ft",
    },
    {
      id: 6,
      title: "Panasonic India Ltd. – Gurgaon",
      images: [],
      description: "Regional office with integrated MEP works.",
      client: "Panasonic India Ltd.",
      location: "Gurgaon",
      architect: "Thai Real Ventures Co. Ltd., Bangkok",
      value: "₹5.48 Cr",
      duration: "3.5 Months",
      scope: "Interior & MEP Works",
      area: "23,750 sq.ft",
    },
    {
      id: 7,
      title: "IBM Tech Park – Tower B",
      images: [],
      description: "IT corporate campus workspace.",
      client: "IBM",
      location: "Pune",
      architect: "Vijay Punjabi Consultants Pvt. Ltd., Mumbai",
      value: "₹3.29 Cr",
      duration: "4 Months",
      scope: "Interior Works",
      area: "1,50,000 sq.ft",
    },
    {
      id: 8,
      title: "Tata Consultancy Services – Borivali",
      images: [],
      description: "Corporate office interiors for TCS.",
      client: "Tata Consultancy Services",
      location: "Mumbai",
      architect: "Vijay Punjabi Consultants Pvt. Ltd., Mumbai",
      value: "₹3.65 Cr",
      duration: "6 Months",
      scope: "Interior Works",
      area: "1,15,000 sq.ft",
    },
    {
      id: 9,
      title: "Honeywell Automation (I) Ltd. – Hadapsar Campus",
      images: [],
      description: "Automation technology corporate campus.",
      client: "Honeywell Automation (I) Ltd.",
      location: "Pune",
      architect: "Axis Associates, Pune",
      value: "₹6.75 Cr",
      duration: "25 Months",
      scope: "Interior Works",
      area: "2,85,000 sq.ft",
    },
    {
      id: 10,
      title: "WNS Global Services",
      images: [],
      description: "Fast-track corporate interior execution.",
      client: "WNS Global Services",
      location: "Pune",
      architect: "Vijay Punjabi Consultants Pvt. Ltd., Mumbai",
      value: "₹1.58 Cr",
      duration: "1.5 Months",
      scope: "Interior Works",
      area: "45,000 sq.ft",
    },
    {
      id: 11,
      title: "Tata Consultancy Services – Pune",
      images: [],
      description: "Corporate workspace interiors.",
      client: "Tata Consultancy Services",
      location: "Pune",
      architect: "Vijay Punjabi Consultants Pvt. Ltd., Mumbai",
      value: "₹2.12 Cr",
      duration: "3 Months",
      scope: "Interior Works",
      area: "70,000 sq.ft",
    },
    {
      id: 12,
      title: "Tata Consultancy Services – Malad",
      images: [],
      description: "Corporate interiors for IT operations.",
      client: "Tata Consultancy Services",
      location: "Mumbai",
      architect: "Vijay Punjabi Consultants Pvt. Ltd., Mumbai",
      value: "₹1.70 Cr",
      duration: "4 Months",
      scope: "Interior Works",
      area: "50,000 sq.ft",
    },
    {
      id: 13,
      title: "Organon India Ltd.",
      images: [],
      description: "Pharmaceutical corporate office interiors.",
      client: "Organon India Ltd.",
      location: "Mumbai",
      architect: "Vijay Punjabi Consultants Pvt. Ltd., Mumbai",
      value: "₹1.10 Cr",
      duration: "2 Months",
      scope: "Interior Works",
      area: "14,500 sq.ft",
    },
    {
      id: 14,
      title: "Jacobs H&G Ltd.",
      images: [],
      description: "Engineering consultancy corporate office.",
      client: "Jacobs H&G Ltd.",
      location: "Mumbai",
      architect: "Hafiz Contractor, Mumbai",
      value: "₹2.66 Cr",
      duration: "4 Months",
      scope: "Interior Works",
      area: "45,000 sq.ft",
    },
    {
      id: 15,
      title: "Cadila Healthcare Ltd. – Mumbai",
      images: [],
      description: "Healthcare corporate office interiors.",
      client: "Cadila Healthcare Ltd.",
      location: "Mumbai",
      architect: "Vijay Punjabi Consultants Pvt. Ltd., Mumbai",
      value: "₹2.15 Cr",
      duration: "3 Months",
      scope: "Interior Works",
      area: "16,500 sq.ft",
    },
    {
      id: 16,
      title: "Cadila Healthcare Ltd. – Ahmedabad",
      images: [],
      description: "Regional healthcare corporate office.",
      client: "Cadila Healthcare Ltd.",
      location: "Ahmedabad",
      architect: "Vijay Punjabi Consultants Pvt. Ltd., Mumbai",
      value: "₹1.60 Cr",
      duration: "4 Months",
      scope: "Interior Works",
      area: "25,000 sq.ft",
    },
    {
      id: 17,
      title: "Central Bank of India",
      images: [],
      description: "Banking corporate office interiors.",
      client: "Central Bank of India",
      location: "Mumbai",
      architect: "Vijay Punjabi Consultants Pvt. Ltd., Mumbai",
      value: "₹3.25 Cr",
      duration: "3 Months",
      scope: "Interior / Electrical Works",
      area: "45,000 sq.ft",
    },
    {
      id: 18,
      title: "Sybase Incorporation",
      images: [],
      description: "Technology corporate office interiors.",
      client: "Sybase Incorporation",
      location: "Pune",
      architect: "Nitin Parulekar Architects Pvt. Ltd., Mumbai",
      value: "₹1.45 Cr",
      duration: "3 Months",
      scope: "Interior Works",
      area: "21,000 sq.ft",
    },
    {
      id: 19,
      title: "Timken India",
      images: [],
      description: "Manufacturing corporate office interiors.",
      client: "Timken India",
      location: "Chennai",
      architect: "Vijay Punjabi Consultants Pvt. Ltd., Mumbai",
      value: "₹1.25 Cr",
      duration: "2 Months",
      scope: "Interior Works",
      area: "14,500 sq.ft",
    },
    {
      id: 20,
      title: "Gillette India Ltd.",
      images: [],
      description: "FMCG corporate office interiors.",
      client: "Gillette India Ltd.",
      location: "Mumbai",
      architect: "Vijay Punjabi Consultants Pvt. Ltd., Mumbai",
      value: "₹0.95 Cr",
      duration: "2 Months",
      scope: "Interior / MEP Works",
      area: "9,000 sq.ft",
    },
    {
      id: 21,
      title: "Indorama Synthetics (I) Ltd.",
      images: [],
      description: "Industrial corporate office interiors.",
      client: "Indorama Synthetics (I) Ltd.",
      location: "Mumbai",
      architect: "Gherzi Eastern Ltd., Mumbai",
      value: "₹1.10 Cr",
      duration: "4 Months",
      scope: "Interior Works",
      area: "21,000 sq.ft",
    },
    {
      id: 22,
      title: "Tristar Jewellery Exports",
      images: [],
      description: "Jewellery export corporate office interiors.",
      client: "Tristar Jewellery Exports",
      location: "Mumbai",
      architect: "Vijay Punjabi Consultants Pvt. Ltd., Mumbai",
      value: "₹1.45 Cr",
      duration: "3 Months",
      scope: "Interior Works",
      area: "18,500 sq.ft",
    },
    {
      id: 23,
      title: "Prasad Film Labs",
      images: [],
      description: "Film production corporate facility.",
      client: "Prasad Film Labs",
      location: "Mumbai",
      architect: "Urban Design Cell, Mumbai",
      value: "₹1.50 Cr",
      duration: "4 Months",
      scope: "Interior Works",
      area: "16,000 sq.ft",
    },
    {
      id: 24,
      title: "Dhruve Liladhar & Co.",
      images: [],
      description: "Professional services corporate office.",
      client: "Dhruve Liladhar & Co.",
      location: "Mumbai",
      architect: "Designers Group, Mumbai",
      value: "₹0.85 Cr",
      duration: "3 Months",
      scope: "Interior Works",
      area: "9,000 sq.ft",
    },
    {
      id: 25,
      title: "SBI General Insurance Pvt. Ltd.",
      images: [],
      description: "Insurance corporate office interiors.",
      client: "SBI General Insurance Pvt. Ltd.",
      location: "Mumbai",
      architect: "Ratan J Batliboi Consultants, Mumbai",
      value: "₹1.26 Cr",
      duration: "3 Months",
      scope: "Interior & MEP Works",
      area: "9,000 sq.ft",
    },
    {
      id: 26,
      title: "Basis Point Securities Pvt. Ltd.",
      images: [],
      description: "Financial services corporate office.",
      client: "Basis Point Securities Pvt. Ltd.",
      location: "Mumbai",
      architect: "Vijay Punjabi Consultants Pvt. Ltd., Mumbai",
      value: "₹1.15 Cr",
      duration: "2 Months",
      scope: "Interior & MEP Works",
      area: "8,500 sq.ft",
    },
    {
      id: 27,
      title: "Reliance Capital Ltd.",
      images: [],
      description: "Turnkey corporate office project.",
      client: "Reliance Capital Ltd.",
      location: "Mumbai",
      architect: "In House",
      value: "₹2.45 Cr",
      duration: "2 Months",
      scope: "Turnkey Project",
      area: "14,500 sq.ft",
    },
  ];

  return (
    <CategoryPage
      title="Corporate"
      tagline="Inspiring Workspaces"
      projects={projects}
    />
  );
};

export default Corporate;
