import CategoryPage, { Project } from "./CategoryPage";

const Hospitality = () => {
  const projects: Project[] = [
    {
      id: 1,
      title: "Hotel Fairmont – Andheri",
      images: [],
      description: "Interior works for luxury hotel.",
      client: "Hotel Fairmont",
      location: "Mumbai",
      architect: "P49 Deesign, Bangkok",
      value: "INR 2495 Lacs",
      duration: "12 Months",
      scope: "Guest Rooms, Suite Rooms, ADD, Business Centre, Meeting Rooms",
      area: "-",
    },
    {
      id: 2,
      title: "Radisson Blu",
      images: [],
      description: "Interior works for premium hotel.",
      client: "Radisson Blu",
      location: "Nashik",
      architect: "Studio HBA",
      value: "INR 3985 Lacs",
      duration: "11 Months",
      scope: "Guest Rooms, Public Areas",
      area: "-",
    },
    {
      id: 3,
      title: "Marriott Executive Apartments",
      images: [],
      description: "Interior works for serviced apartments.",
      client: "Marriott Executive Apts.",
      location: "Navi Mumbai",
      architect: "PG Patki Architects, Mumbai",
      value: "INR 2653 Lacs",
      duration: "12 Months",
      scope: "Guest Rooms, Public Areas",
      area: "-",
    },
    {
      id: 4,
      title: "Hotel Cidade De Goa",
      images: [],
      description: "Interior works for beach resort.",
      client: "Hotel Cidade De Goa",
      location: "Goa",
      architect: "Studio IV Designs, New Delhi",
      value: "INR 2125 Lacs",
      duration: "7 Months",
      scope: "Guest Rooms & Corridor",
      area: "-",
    },
    {
      id: 5,
      title: "Club Mahindra",
      images: [],
      description: "Interior works for resort property.",
      client: "Club Mahindra",
      location: "Goa",
      architect: "PG Patki Architects, Mumbai",
      value: "INR 4350 Lacs",
      duration: "15 Months",
      scope: "Guest Rooms, Public Areas, Hardscape",
      area: "-",
    },
    {
      id: 6,
      title: "Hotel Fairfield Marriott",
      images: [],
      description: "Interior works for business hotel.",
      client: "Hotel Fairfield Marriott",
      location: "Mumbai",
      architect: "Designers Group, Mumbai",
      value: "INR 2135 Lacs",
      duration: "9 Months",
      scope: "Guest Rooms, Public Areas",
      area: "-",
    },
    {
      id: 7,
      title: "Hotel Fairfield Marriott (FFM)",
      images: [],
      description: "Interior works for hotel.",
      client: "Hotel Fairfield Marriott",
      location: "Mumbai",
      architect: "PG Patki Architects, Mumbai",
      value: "INR 1635 Lacs",
      duration: "11 Months",
      scope: "Guest Rooms, Public Areas",
      area: "-",
    },
    {
      id: 8,
      title: "Hilton Garden Inn",
      images: [],
      description: "Interior works for international hotel.",
      client: "Hilton Garden Inn",
      location: "Mumbai",
      architect: "FBEYE International Pte. Ltd., Singapore",
      value: "INR 1685 Lacs",
      duration: "9 Months",
      scope: "Guest Rooms, Public Area",
      area: "-",
    },
    {
      id: 9,
      title: "Hotel Four Points Sheraton",
      images: [],
      description: "Interior works for hotel.",
      client: "Four Points Sheraton",
      location: "Chennai",
      architect: "Leo Design Group, Bangkok",
      value: "INR 1385 Lacs",
      duration: "8 Months",
      scope: "Guest Rooms",
      area: "-",
    },
    {
      id: 10,
      title: "Hotel Four Points Sheraton",
      images: [],
      description: "Interior works for hotel.",
      client: "Four Points Sheraton",
      location: "Nashik",
      architect: "ARK Reza Kabul Architects",
      value: "INR 1275 Lacs",
      duration: "15 Months",
      scope: "Guest Rooms, Public Areas",
      area: "-",
    },
    {
      id: 11,
      title: "Hotel Novotel Imagica",
      images: [],
      description: "Interior works for theme hotel.",
      client: "Novotel",
      location: "Khopoli",
      architect: "Bharat Shetty Architects, Mumbai",
      value: "INR 2472 Lacs",
      duration: "8 Months",
      scope: "Guest Rooms, Public Areas",
      area: "-",
    },
    {
      id: 12,
      title: "Hotel Renaissance",
      images: [],
      description: "Interior works for luxury hotel.",
      client: "Hotel Renaissance",
      location: "Mumbai",
      architect: "P49 Deesign, Bangkok",
      value: "INR 977 Lacs",
      duration: "6 Months",
      scope: "Guest Rooms",
      area: "-",
    },
    {
      id: 13,
      title: "Hotel Four Points Sheraton",
      images: [],
      description: "Interior works for hotel.",
      client: "Four Points Sheraton",
      location: "Vizag",
      architect: "Total Integrated Design (India) Pvt. Ltd., Gurgaon",
      value: "INR 1050 Lacs",
      duration: "9 Months",
      scope: "Guest Rooms, Public Areas",
      area: "-",
    },
    {
      id: 14,
      title: "Hotel Holiday-Inn",
      images: [],
      description: "Interior works for hotel.",
      client: "Holiday-Inn",
      location: "Mumbai",
      architect: "P49 Deesign, Bangkok",
      value: "INR 815 Lacs",
      duration: "4 Months",
      scope: "Suites, Guest Rooms",
      area: "-",
    },
    {
      id: 15,
      title: "Fariyas Holiday Resorts",
      images: [],
      description: "Interior works for resort.",
      client: "Fariyas Holiday Resorts",
      location: "Lonavala",
      architect: "Designers Group, Mumbai",
      value: "INR 1075 Lacs",
      duration: "6 Months",
      scope: "Public Areas, Suites, Guest Rooms, Banquets",
      area: "-",
    },
    {
      id: 16,
      title: "The Resort",
      images: [],
      description: "Interior works for resort property.",
      client: "The Resort",
      location: "Mumbai",
      architect: "PG Patki Architects, Mumbai",
      value: "INR 645 Lacs",
      duration: "6 Months",
      scope: "Guest Rooms, Public Area, Banquets / BOH",
      area: "-",
    },
    {
      id: 17,
      title: "The Orchid Hotel",
      images: [],
      description: "Interior works for hotel.",
      client: "The Orchid Hotel",
      location: "Mumbai",
      architect: "Lynn Wilson International, USA",
      value: "INR 625 Lacs",
      duration: "10 Months",
      scope: "Suites / Guest Rooms",
      area: "-",
    },
    {
      id: 18,
      title: "The Orchid Hotel",
      images: [],
      description: "Interior works for hotel.",
      client: "The Orchid Hotel",
      location: "Pune",
      architect: "Upasni Design Cell, Mumbai",
      value: "INR 1075 Lacs",
      duration: "3 Months",
      scope: "Guest Rooms / Banquets",
      area: "-",
    },
    {
      id: 19,
      title: "Fort Jadhav Gadh Heritage Hotel",
      images: [],
      description: "Interior works for heritage hotel.",
      client: "Kamat Hotels",
      location: "Pune",
      architect: "Karan Grover Associates, Vadodara",
      value: "INR 135 Lacs",
      duration: "3 Months",
      scope: "Public Areas / Restaurants, Museum",
      area: "-",
    },
    {
      id: 20,
      title: "Hotel Grand Hyatt",
      images: [],
      description: "Interior works for luxury hotel.",
      client: "Grand Hyatt",
      location: "Mumbai",
      architect: "Chhada Siembieda Remedies, California",
      value: "INR 481 Lacs",
      duration: "6 Months",
      scope: "Suites, Guest Rooms, Service Apartments",
      area: "-",
    },
    {
      id: 21,
      title: "Layana Resort with Times Enterprise",
      images: [],
      description: "Interior works for resort.",
      client: "Layana Resort",
      location: "Lanta, Krabi",
      architect: "August Design Construction, Bangkok",
      value: "THB 45 Mn",
      duration: "10 Months",
      scope: "Timber Roof Structure",
      area: "-",
    },
    {
      id: 22,
      title: "Royal Garden Plaza with Times Enterprise",
      images: [],
      description: "Interior works for food court.",
      client: "Royal Garden Plaza",
      location: "Pattaya",
      architect: "Urban Architects, Bangkok",
      value: "THB 21 Mn",
      duration: "4 Months",
      scope: "Wave Food Court",
      area: "-",
    },
    {
      id: 23,
      title: "Amarin Plaza",
      images: [],
      description: "Interior works for public areas.",
      client: "Amarin Plaza",
      location: "Bangkok",
      architect: "Urban Architects, Bangkok",
      value: "THB 12.5 Mn",
      duration: "5 Months",
      scope: "Lobby & Public Areas",
      area: "-",
    },
    {
      id: 24,
      title: "Butlers Coffee Shop at Gaysorn Lobby",
      images: [],
      description: "Interior works for coffee shop.",
      client: "Butlers Coffee Shop",
      location: "Bangkok",
      architect: "Onion Design, Bangkok",
      value: "THB 2.5 Mn",
      duration: "2 Months",
      scope: "Coffee Shop",
      area: "-",
    },
    {
      id: 25,
      title: "Banyan Golf Club",
      images: [],
      description: "Interior works for clubhouse.",
      client: "Banyan Golf Club",
      location: "Hua Hin",
      architect: "OBA, Bangkok",
      value: "THB 21.2 Mn",
      duration: "3 Months",
      scope: "Club House / Restaurant / Pub",
      area: "-",
    },
    {
      id: 26,
      title: "IZA – Japanese Restaurant",
      images: [],
      description: "Interior & MEP works.",
      client: "IZA Restaurant",
      location: "Bangkok",
      architect: "Thai Real Ventures Co. Ltd., Bangkok",
      value: "THB 6.5 Mn",
      duration: "2 Months",
      scope: "Interior / MEP Works",
      area: "-",
    },
    {
      id: 27,
      title: "Ping’s Sharkfin Restaurant",
      images: [],
      description: "Interior & MEP works.",
      client: "Ping’s Sharkfin Restaurant",
      location: "Bangkok",
      architect: "ED Design Group, Singapore",
      value: "THB 13.5 Mn / 6.5 Mn",
      duration: "3 / 2 Months",
      scope: "Interior / MEP Works",
      area: "-",
    },
    {
      id: 28,
      title: "Hotel Grand President with Times Enterprise",
      images: [],
      description: "Interior works for hotel.",
      client: "Hotel Grand President",
      location: "Bangkok",
      architect: "Leo International, Bangkok",
      value: "THB 10.5 Mn",
      duration: "3 Months",
      scope: "Guest Rooms",
      area: "-",
    },
  ];

  return (
    <CategoryPage
      title="Hotels & Resorts"
      tagline="Unforgettable Stays"
      projects={projects}
    />
  );
};

export default Hospitality;
